### PR TITLE
revisions to issues and suggestions

### PR DESCRIPTION
**Pull request by SammyOina**
- VCC and ground directions
 - Logo silkscreen
 - 7.4 to 5v regulator removed

### CODE REVIEW

**Comment by 0x6f736f646f** [comment]
Screenshot from 2022-01-25 17-14-20

What is the forward voltage drop of the LED?
What is your desired current?

Because we use the 470 Ohm resistor on a previous design and our power source was 3.3v. I think for 5 volts it will be brighter. Or that is your intention?

@Mike-Kimani You can confirm on this

**Comment by 0x6f736f646f** [comment]
# MPU6050 VDD

Stil on the MPU6050 VDD is downfacing

You can use this approach or even you can place all the decoupling capacitor in one place then name respectively

Screenshot from 2022-01-25 17-19-11

**Comment by 0x6f736f646f** [comment]
# Mounting hole recommendations

Check out this [comment](https://github.com/nakujaproject/flight-control-computer/issues/8#issuecomment-1021233847)

**Review by 0x6f736f646f — CHANGES_REQUESTED** [review]
Check the suggestions

**Comment by 0x6f736f646f** [comment]
Resolves #5

**Comment by 0x6f736f646f** [comment]
Resolves #7

**Comment by 0x6f736f646f** [comment]
Resolves #8

**Comment by 0x6f736f646f** [comment]
Resolves #3

**Comment by 0x6f736f646f** [comment]
Resolves #11

**Review by 0x6f736f646f — CHANGES_REQUESTED** [review]
Requested some minor changes

**Comment by 0x6f736f646f** [comment]
Resolves #14

**Review by SammyOina — COMMENTED** [review]
C307416 is 10uF not 0.1uF

**Comment by 0x6f736f646f** [comment]
Resolves #13

**Comment by 0x6f736f646f** [comment]
> C307416

I have change with C83054

Check out https://github.com/nakujaproject/flight-control-computer/pull/12/commits/2a5377db8bf3db9744977f2ea4192be57d4a76ab

**Review by 0x6f736f646f — CHANGES_REQUESTED** [review]
Review the new changes and update the PCB accordingly.

**Comment by 0x6f736f646f** [comment]
Resolves #2

**Review by 0x6f736f646f — APPROVED** [review]

**Pull request merged**
